name: Build_Unreal_Plugin_Example

on: workflow_dispatch

env:
  CPP_SDK_TAG: "2.4.2"
  CPP_SDK_DESTINATION: "Millicast"
  CPP_SDK_URL: "https://github.com/DolbyIO/comms-sdk-cpp/releases/download"
  UNREAL_PLUGIN_OUTPUT: "Build/Millicast"
  RETENTION: 7

jobs:
  build-linux:
    strategy:
      fail-fast: false
      matrix:
        version: ["4.27", "5.0", "5.1"]
    runs-on: ["self-hosted", "X64", "macOS"]
    env:
      BUILD_PLATFORM: 'linux'
    steps:
      - name: test
        run: |
          echo "this is test on linux"


  build-windows:
    strategy:
      fail-fast: false
      matrix:
        version: ["4.27", "5.0", "5.1"]
    runs-on: ["self-hosted", "X64", "Windows"]
    env:
      BUILD_PLATFORM: 'windows64'
    steps:
      - name: test
        run: |
          echo "this is test on windows"
